### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by mohitgargk** [bkeiren/AwesomiumUnity#1]
I just tried your Awesomium wrapper for Unity 4.5. Unfortunately, the Unity is crashing when I try to play.

Can you provide any support of your plugin/package or guide Awesomium-Unity integration.

**Comment by bkeiren** [comment]
Hi mohitgargk!

I can take a look at this issue later today. However, please keep in mind that it is possible that when I wrote this wrapper Unity was still on an earlier version. This could cause incompatibility issues such as you are experiencing. If this is the case I can take a look into updating for the current version of Unity, but I can't make any promises as my time is quite constrained.

Cheers

**Comment by bkeiren** [comment]
Hello mohitgark, 

My apologies for the late response, I've been rather preoccupied lately. 

However if you are still interested I am here to tell you that there will be an update to the repo soon (in a few days. The code is done and waiting for submission), which will implement a large number of new features as well as major bug fixes. This should fix the crashes you were having. 

Please keep an eye out for these changes! 

Cheers
