### ISSUE TITLE
Unity3D: Not working at all

### ISSUE THREAD

**Issue by sumeetkpatel** [bkeiren/AwesomiumUnity#5]
Has anyone been able to get anything working at all with this recently? I am simply getting black textures and nothing happens (for example WebTextures, with the script component attached).

I am using Unity 5 on Windows 7 64bit.

**Comment by TheMajorO** [comment]
@sumeetkpatel  
You need to have 32-bit version of Unity...
![unity_awesomium](https://cloud.githubusercontent.com/assets/13148907/8474363/68e83572-2064-11e5-862f-ddeb8807d680.PNG)

**Comment by bkeiren** [comment]
Issue addressed by @TheMajorO.
